# Generated by Django 3.0.7 on 2020-06-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_contact_category', models.CharField(choices=[('RE', 'Restaurant'), ('CO', 'Coffee'), ('PU', 'Pub'), ('CE', 'Wine Cellar')], default='CO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Bar name')),
                ('bar_type', models.ManyToManyField(to='services.BarType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
