# Generated by Django 3.0.7 on 2020-06-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bartype',
            old_name='phone_contact_category',
            new_name='bar_type_category',
        ),
    ]
