# Generated by Django 3.0.7 on 2020-06-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200617_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='bar_type',
        ),
        migrations.AddField(
            model_name='bar',
            name='bar_type',
            field=models.CharField(choices=[('RE', 'Restaurant'), ('CO', 'Coffee'), ('PU', 'Pub'), ('CE', 'Wine Cellar')], default='', max_length=2, verbose_name='Bar type'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BarType',
        ),
    ]
