# Generated by Django 3.0.7 on 2020-06-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200617_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='zip_code',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
