# Generated by Django 3.0.7 on 2020-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_bar_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='zip_code',
            field=models.CharField(max_length=16),
        ),
    ]
